Bttribev2 10270 range slider
AnyVisionltd/anv-ui-components pull request #271
Opened 2021-08-16 13:45 UTC by AdimAnyvision

## What I did

## How to test

### Checklist
- [ ] Does this need a new/update storybook example?
- [ ] Does this need new/update tests?

- [ ] run eslint
- [ ] run test
- [ ] run build

If your answer is yes to any of these, please make sure to include it in your PR.

> NOTE: Please submit all PRs to the `development` branch.

2021-08-19 11:16 UTC, ozAnyvision requested changes
@IrenaSAnyVision can you please review the PR as well?

2021-08-19 11:16 UTC, ozAnyvision commented on src/components/RangeSlider/RangeSlider.js
> +  sliderWidth: propTypes.number,
Didn't we discuss about the width and said it's not needed?

2021-08-19 11:49 UTC, AdimAnyvision commented on src/components/RangeSlider/RangeSlider.js
> +  sliderWidth: propTypes.number,
It iinitially was with fixed widths (144, 240, 360, 480, 640, 960) and as far as I remember we said we will allow the width to be determined manually.
With the disabled, I don't remember. I removed the isDarkTheme prop. 
Do you want me to remove both of the props ?

2021-08-19 11:49 UTC, AdimAnyvision commented on src/components/RangeSlider/RangeSlider.js
> +import classNames from 'classnames'
Ok, I will change

2021-08-19 17:17 UTC, IrenaSAnyVision requested changes

2021-08-19 17:17 UTC, IrenaSAnyVision commented on src/components/RangeSlider/RangeSlider.js
> +  }
```suggestion
  const renderTooltip = () => (!isToggleTooltip || showTooltip) ? (
    <div ref={tooltipRef} className={styles.tooltip}>
      {hoverValue ?? value}
    </div>
  ) : null
  }
```
I think it has the same result - check it and choose what you prefer

2021-08-19 17:19 UTC, IrenaSAnyVision commented on src/components/RangeSlider/RangeSlider.js
> +import React, { useState, useRef, useEffect, useCallback, useMemo } from 'react'
please add a line to the CHANGELOG.md file about your component :)

2021-08-22 12:17 UTC, IrenaSAnyVision requested changes

2021-08-22 12:17 UTC, IrenaSAnyVision commented on src/components/RangeSlider/RangeSlider.js
> +  const renderMeasureUnitText = () => measureUnitText || null
Is the null necessary?

2021-08-22 12:17 UTC, IrenaSAnyVision commented on src/components/RangeSlider/RangeSlider.js
> +    if (e.keyCode === 37 || e.keyCode === 39) {
there is a keymap in: utils/enums/keymap.js
please use it instead of writing 37 or 39 in the code

2021-08-23 12:21 UTC, IrenaSAnyVision requested changes

2021-08-23 12:21 UTC, IrenaSAnyVision commented on CHANGELOG.md
> +- New Range Slider.
Almost XD
The file is separated by the package versions..
You added your "text" to version 0.1.3 (that was released on September last year)
You should add it to "Added" part of "Unreleased" version (line 39)

And please write it as on line 38..

2021-08-23 12:21 UTC, IrenaSAnyVision commented on src/components/RangeSlider/RangeSlider.js
> +    if (e.keyCode === keymap.ARROW_LEFT || e.keyCode === keymap.ARROW_RIGHT) {
```suggestion
    if ([keymap.ARROW_LEFT, keymap.ARROW_RIGHT].includes(e.keyCode)) {
```
Another way to write it (choose what you prefer - I don't mind)

2021-08-23 12:21 UTC, IrenaSAnyVision commented on src/components/RangeSlider/RangeSlider.js
> +import keymap from '../../utils/enums/keymap'
I still do not see the export of the component......

2021-08-23 12:21 UTC, IrenaSAnyVision commented on src/components/RangeSlider/RangeSlider.js
> +    if (e.keyCode === keymap.ARROW_LEFT || e.keyCode === keymap.ARROW_RIGHT) {
please try to press the keys UP & DOWN or HOME & END or PG UP & PG DN
For my experiments they all moves the "circle" but it does not affect the "tooltip" above

2021-08-25 10:52 UTC, IrenaSAnyVision approved these changes

2021-08-25 11:40 UTC, IrenaSAnyVision approved these changes

2021-08-25 11:53 UTC, ozAnyvision approved these changes

2021-08-25 11:53 UTC, merged