BTTRIBEV2-11252 no results indication
AnyVisionltd/anv-ui-components pull request #317
Opened 2021-12-01 11:00 UTC by AdimAnyvision

## What I did

## How to test

### Checklist
- [ ] Does this need a new/update storybook example?
- [ ] Does this need new/update tests?

- [ ] run eslint
- [ ] run test
- [ ] run build

If your answer is yes to any of these, please make sure to include it in your PR.

> NOTE: Please submit all PRs to the `development` branch.

2021-12-01 14:46 UTC, orelHAnyvision commented on src/components/Tree/Tree.js
> +    if (!searchQuery) return false
tree is empty if there are not items at all... doesn't matter if visible or not
split the "empty" state to two: none or none found

2021-12-01 14:46 UTC, orelHAnyvision commented on src/components/Tree/EmptyTreeSearch/EmptyTreeSearch.js
> +  onClearSearch: propTypes.func,
```suggestion
  onClearSearch: propTypes.func
```

2021-12-01 14:46 UTC, orelHAnyvision commented on src/components/Tree/EmptyTreeSearch/EmptyTreeSearch.js
> +  onClearSearch: () => {},
```suggestion
  onClearSearch: () => {}
``

2021-12-01 14:50 UTC, orelHAnyvision requested changes
use TextField instead of InputBase
change empty result behaviour

:)

2021-12-02 07:41 UTC, AdimAnyvision commented on src/components/Tree/EmptyTreeSearch/EmptyTreeSearch.js
> +  onClearSearch: () => {},
It's the linter

2021-12-02 07:41 UTC, AdimAnyvision commented on src/components/Tree/EmptyTreeSearch/EmptyTreeSearch.js
> +  onClearSearch: propTypes.func,
It's the linter

2021-12-02 15:30 UTC, moshekanyvision requested changes

2021-12-02 15:30 UTC, moshekanyvision commented on src/components/Tree/EmptyTreeSearch/EmptyTreeSearch.js
> +})
Should this be here, or in the utils file you created?

2021-12-02 15:31 UTC, AdimAnyvision commented on src/components/Tree/EmptyTreeSearch/EmptyTreeSearch.js
> +})
Good idea, will change location of the variable

2021-12-02 15:38 UTC, moshekanyvision approved these changes

2021-12-02 15:38 UTC, merged