BTTRIBEV2-11240 add tests
AnyVisionltd/anv-ui-components pull request #319
Opened 2021-12-02 15:45 UTC by AdimAnyvision

## What I did

## How to test

### Checklist
- [ ] Does this need a new/update storybook example?
- [ ] Does this need new/update tests?

- [ ] run eslint
- [ ] run test
- [ ] run build

If your answer is yes to any of these, please make sure to include it in your PR.

> NOTE: Please submit all PRs to the `development` branch.

2021-12-02 16:24 UTC, moshekanyvision requested changes

2021-12-02 16:24 UTC, moshekanyvision commented on src/components/Tree/Tree.test.js
> +  test('`select all` checkbox should be checked when all nodes are selected', () => {
Can you refactor these to be in a describe of their own for search, selection, or other functionalities this component has?
example:
describe ('search', () => {})
describe ('select', () => {})
...
etc

2021-12-02 16:31 UTC, AdimAnyvision commented on src/components/Tree/Tree.test.js
> +  test('`select all` checkbox should be checked when all nodes are selected', () => {
Sure

2021-12-05 09:55 UTC, closed without merging

2021-12-05 09:55 UTC, AdimAnyvision commented
Changes were merged in the next pr