BTTRIBEV2-10838-Toast_Message_-_New_Component
AnyVisionltd/anv-ui-components pull request #320
Opened 2021-12-02 16:41 UTC by IdanBAnyvision

## What I did

## How to test

### Checklist
- [ ] Does this need a new/update storybook example?
- [ ] Does this need new/update tests?

- [ ] run eslint
- [ ] run test
- [ ] run build

If your answer is yes to any of these, please make sure to include it in your PR.

> NOTE: Please submit all PRs to the `development` branch.

2021-12-05 09:25 UTC, orelHAnyvision commented on package.json
> +    "react-dom": "^16.14.0"
why did you upgrade so many libraries?

2021-12-05 09:26 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +    if (hideTimeout === null) {
```suggestion
    if (!hideTimeout) {
```

2021-12-05 09:27 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +  }
```suggestion
  const renderUndoButton = () => 
      isUndo &&
      <Button className={classNames(styles.undoButton)} onClick={undoCallback} variant='ghost'
              size='small'>undo</Button>
```

2021-12-05 09:27 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +              size='small'>undo</Button>
please use language service for texts

2021-12-05 09:28 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +      <Button className={classNames(styles.undoButton)} onClick={undoCallback} variant='ghost'
if only one class you can remove classNames function

2021-12-05 09:28 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +    [styles[type]]: !!type,
what can be 'type' ?

2021-12-05 09:29 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +import toastMessageTypeMapper from './ToastMessage.utils'
reorder
3d libraries
functions
internal components
scss

2021-12-05 09:29 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +  const timerHide = React.useRef()
import useRef

```suggestion
  const timerHide = useRef()
```

2021-12-05 09:31 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +  height: 72px;
use var please. if doesn't exists please talk to Michael

2021-12-05 09:31 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +    border: solid 1px av-color(error);
use var please. if doesn't exists please talk to Michael

2021-12-05 09:32 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +      width: 2.5em;
usr vars

2021-12-05 09:32 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +    margin: 0 10px;
var.... av-space

2021-12-05 09:34 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.stories.js
> +import { Button } from '../Button'
reorder

2021-12-05 09:35 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.stories.js
> +        isUndo={true}
```suggestion
        isUndo
```

2021-12-05 09:35 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.test.js
> +import { ReactComponent as SunIcon } from '../../assets/svg/Sun.svg'
import from anv-icons...

2021-12-05 09:35 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +import { ReactComponent as CloseIcon } from '../../assets/svg/Close.svg'
import from anv-icons

2021-12-05 09:49 UTC, orelHAnyvision requested changes
please also add space before/after brackets {}

2021-12-05 10:35 UTC, IdanBAnyvision commented on package.json
> +    "react-dom": "^16.14.0"
@orelHAnyvision - I didn't really upgrade any library, I just updated it to be the version that was already installed by npm.

2021-12-05 10:46 UTC, IdanBAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +    [styles[type]]: !!type,
@orelHAnyvision - type can be one of these - 'success', 'info', 'error', 'alert'

2021-12-05 11:57 UTC, IdanBAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +  height: 72px;
@orelHAnyvision - I talked to Michael and he asked me to add 2 sizes (sz-64 and sz-8 in order to get 72), this is how i did this:
`  height: calc(#{av-size(sz-64)} + #{av-size(sz-8)});`

2021-12-05 12:05 UTC, IdanBAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +    border: solid 1px av-color(error);
@orelHAnyvision - for what exactly should I use var? 
for the `-6px` ?
If so, this size doesn't exist.
and we don't a way to combine 2 existing sizes to get 6px.

2021-12-05 13:11 UTC, IdanBAnyvision commented
@orelHAnyvision - I fixed all your comments. Thanks for the review.

regarding this comment - _add space before/after brackets {}_ - Ira said that this is not needed in this repo...

2021-12-05 13:39 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +    [styles[type]]: !!type,
so !! will always be true.... whats is the meaning of this condition?
also add proptypes of oneOf for that type

2021-12-05 13:40 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.stories.js
> +        isOpen
???? why isOpen always true?
I think you confused..

2021-12-05 13:49 UTC, IdanBAnyvision commented on src/components/ToastMessage/ToastMessage.stories.js
> +        isOpen
@orelHAnyvision - fixed and pushed a new commit

2021-12-05 15:27 UTC, IdanBAnyvision commented
@orelHAnyvision - fixed and pushed a new commit

2021-12-05 17:00 UTC, IrenaSAnyVision commented on CHANGELOG.md
> +- storybook 6.1.14 -> 6.1.21
I think there is no need to put it there

2021-12-06 11:54 UTC, orelHAnyvision commented on package.json
> +    "react-dom": "^16.14.0"
do you use node 12 or 14?

2021-12-06 11:54 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +  --undo-button-margin: 10px;
av space

2021-12-06 11:55 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +      width: var(--svg-size);
av-size...

2021-12-06 11:56 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.utils.js
> +}
```suggestion
const toastMessageTypeMapper = type => map[type]
```

2021-12-06 11:57 UTC, orelHAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +
```suggestion
```

2021-12-06 12:17 UTC, IdanBAnyvision commented on CHANGELOG.md
> +- storybook 6.1.14 -> 6.1.21
@IrenaSAnyVision - ok - removed.

2021-12-06 12:18 UTC, IdanBAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +  --undo-button-margin: 10px;
@orelHAnyvision - we don't have these sizes in the styleguide. so I cannot use av-space...

2021-12-06 12:18 UTC, IdanBAnyvision commented on src/components/ToastMessage/ToastMessage.module.scss
> +      width: var(--svg-size);
@orelHAnyvision - same as my comment above.

2021-12-06 13:44 UTC, IdanBAnyvision commented
@orelHAnyvision - ok, I updated a few more things based on Michael feedback, but 1 variable was still needed since this is a specific value for this component:

```
:root {
  --box-shadow-vertical-length: -6px;
}
```

...

2021-12-06 13:57 UTC, IdanBAnyvision commented on src/components/ToastMessage/ToastMessage.js
> +    [styles[type]]: !!type,
@orelHAnyvision - `type: propTypes.oneOf(['success', 'info', 'error', 'alert']),` is already defined as PropTypes.

2021-12-06 15:17 UTC, orelHAnyvision approved these changes

2021-12-06 15:18 UTC, merged